# Compiler and flags
CC = gcc
CFLAGS = -Wall -g
LDFLAGS = -lm
TARGET = task2

# Find all .c files recursively in src/
SRCS := $(shell find src -name '*.c')

all: $(TARGET)

$(TARGET): $(SRCS)
	$(CC) $(CFLAGS) $(SRCS) -o $(TARGET) $(LDFLAGS)

clean:
	rm -f $(TARGET)
